### ISSUE TITLE
BUG - 2D/3D question to ask JLR.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#34]
When user switch to 3D view and select between Orientations, shouldn't map follow user's current position in the Real-Time? For now it's working like the camera is waiting until the position icon disappear and than switch its position, and so on. Just a question, cause I'm not sure how it should work actually.

**Comment by dcranejlr** [comment]
The 3D view should also make the positioning operate in Head-up mode automatically. While in 3D mode the user cannot switch to north up view. I looked at the HMI and this is not clear based on the document. Do you want us to update it to reflect this behavior?

**Comment by mmorale1** [comment]
I agree with Dale. 3D view should always be in Head-up orientation. If the user changes the orientation to North-up, then *Settings > 2D/3D view* should automatically change to 2D. The user should see the map immediately change to 2D / North-up.

**Comment by amcgee7** [comment]
I don't find North-up useful in a car.  I believe that regardless of
weather your in 2D or 3D modes you should be looking from the perspective
or direction of your car.

3D = heads up with camera pointed in the same direction as the car.

2D = Up is the direction your car is headed.

A control to show your compass direction.

Just thought I would put in my 2 cents.

On 15 May 2015 at 13:48, Marco Morales <notifications@github.com> wrote:

> I agree with Dale. 3D view should always be in Head-up orientation. If the
> user changes the orientation to North-up, then *Settings > 2D/3D view*
> should automatically change to 2D. The user should see the map immediately
> change to 2D / North-up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDXostc/navit/issues/34#issuecomment-102522926>.
>



-- 
*Art McGee*
Infotainment Engineer



Jaguar Land Rover North America, LLC
1419 NW 14th Ave, Portland, Oregon, 97209
Jaguar.com <http://jaguar.com>  |  LandRover.com <http://landrover.com>

**Comment by mmorale1** [comment]
Thanks for the feedback Art. One thing is that Head-up view doesn't inform the user what direction they're headed in. And the app has no other output indicating such. North-up view provides that. I know that if I'm pointing toward the right of the screen, I'm heading east.

**Comment by amcgee7** [comment]
The app should have a compass on screen in both 2d and 3d modes.

**Comment by w0land** [comment]
Ok, I'll implement 3D view only in Heads up view.
