### ISSUE TITLE
BUG - No possibility to Tap OFF.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#39]
User is unable to Tap OFF by tapping on not occupied point anywhere on the map.

**Comment by w0land** [comment]
Don't get it. Maybe some steps to reproduce?

**Comment by hubertjadczak** [comment]
Steps from Test 14: Select Location from Point of Interest (directly - step 7 and 8):

1. Verify if Points of Interest are displayed on the map.
2. Tap on random Point of Interest (POI).
3. Verify if information about the point is displayed on the bottom of the screen.
4. Verify if other markers are dimmed.
5. Taps off of location marker and verify if map view remains in current position and selected
markers are made inactive.
6. Verify if all markers are returned to previous appearance.
7. Tap and hold on unmarked point on the map and verify if geo information about selected point is displayed.
8. Taps off anywhere on the map not occupied by a marker and verify if map view remains in current
position and selected markers are made inactive.
