### ISSUE TITLE
BUG - On the top in Country/Language sub-menu track should be displayed.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#45]
Now in Country/Language sub-menu there is only (for example) "Recommended" and according to HMI Flows 2.1 and 2.2 it should be: "Reommended / Country/Language":
![45](https://cloud.githubusercontent.com/assets/10448932/7751877/93ab4de2-ffdc-11e4-9e13-54c9ddda2f72.png)

**Comment by hubertjadczak** [comment]
By "track" I wanted to say "breadcrumb".

**Comment by w0land** [comment]
New download UI
