### ISSUE TITLE
BUG - Orientation is switched automatically on north-up in menu.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#46]
Changing map orientation works when user do it on the map - by clicking orientation button, but in Menu when user set orientation from "north-up" to "follow" go back to map and return to menu the orientation wil be set on "north-up" automatically:
1. By default Orientation is set to north-up.
![46a](https://cloud.githubusercontent.com/assets/10448932/7751821/35d6488e-ffdc-11e4-9679-d550da883cad.png)
2. After change it to "Follow"...
![46b](https://cloud.githubusercontent.com/assets/10448932/7751823/37605ab4-ffdc-11e4-904b-13e9eec98ceb.png)
3. ...go back to map...
![46c](https://cloud.githubusercontent.com/assets/10448932/7751825/38a616ca-ffdc-11e4-88b8-1c13ab4c97d3.png)
4. ...and return to menu, orientation is set to north-up again automatically.
![46d](https://cloud.githubusercontent.com/assets/10448932/7751826/3a11d134-ffdc-11e4-81d4-b56c1de07ad1.png)

**Comment by w0land** [comment]
Should be fixed already
