### ISSUE TITLE
BUG - lack of detailed information about route. No proper distance either.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#48]
When user select a destination point and start the navigation, there is no detailed information about the route. Probably it's a bit too early for this implementation, just letting know.

**Comment by mmorale1** [comment]
Looking at the Navit app, it appears that Navit provides driving distance to destination, direct distance to destination, time to destination, next turn icon, and distance to next turn. I was hoping there was some additional data provided like direction steps (text), current and next turn (text). If some things are not provided, I'll need to update the HMI.

Could you you send me a list of the data that Navit returns?

**Comment by w0land** [comment]
@Marco: Basically what you mentioned. I need to check if it's possible to get a list on next maneuvers,  but my best guess is that's not available. I'll check that tomorrow

**Comment by w0land** [comment]
This was fixed as a part of #9 and #10manuvers
