### ISSUE TITLE
BUG - Recommended instead of Country/Language List items

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#57]
![57](https://cloud.githubusercontent.com/assets/10448932/7749494/39f23bc0-ffce-11e4-9ed9-3a005abea88d.png)
According to HMI Flows 2.2, Use Case 03: Access Settings, page 5/23: Sub-menu is displayed and it contains listed "List Items #", for now Sub-menu contains "Recommended".
I know it's just a tenporary solution, and this is a second time I mention it, but we need to know what exactly there should be, what JLR wants there (it's not specified in HMI Flows).

**Comment by mmorale1** [comment]
We'd like to change "Country/Language" to "Download Maps" in Settings. The sub-menu should list "Downloaded Maps", then "Recommended maps" followed by "Earth" then each continent/region alphabetically. Each continent/region should lead into a sub-menu of countries which leads into a sub-menu of states, etc. A PDF will be sent over.

**Comment by w0land** [comment]
New Map download UI
