### ISSUE TITLE
BUG - "Yes" instead of "Quit" button when "Cancel" during map download is selected.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#58]
When user decide to cancel map download there are two other buttons - confirmation button "Yes" and "Continue Downloading". The problem is there should be "Quit" instead of "Yes".

**Comment by w0land** [comment]
Default 'quit' action makes sense only for FTU not when user have at least one map downloaded. 
Do we really want to quit application if some maps are already downloaded?

**Comment by hubertjadczak** [comment]
Right, "Quit" button should be available only during first-time launch.
