### ISSUE TITLE
BUG - Selecting locations from history causes multiplication of already saved locations.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#62]
When location from history is selected and then user tap OFF selection on not occupied section, then return to Location History, and select again the same location after few trials will notice there is a lot more locations saved in history than should be, for example: I had like 9 the same locations (Northwest Marshall Street 1313) and after selection one of them, after tap OFF and return to location history there were 17 the same locations already:
![62a](https://cloud.githubusercontent.com/assets/10448932/7751751/d14bc10a-ffdb-11e4-8161-a981aa7e9bc6.png)
![62b](https://cloud.githubusercontent.com/assets/10448932/7751756/d4c708a8-ffdb-11e4-8c95-9bd680a97cc7.png)
![62c](https://cloud.githubusercontent.com/assets/10448932/7751758/d79a709c-ffdb-11e4-9cc6-9f094893c600.png)
![62d](https://cloud.githubusercontent.com/assets/10448932/7751759/d8dc1db6-ffdb-11e4-8ca3-fcec139bf862.png)
![62e](https://cloud.githubusercontent.com/assets/10448932/7751761/da62ff92-ffdb-11e4-9197-5c5da6bf6f86.png)

**Comment by w0land** [comment]
Already fixed
