### ISSUE TITLE
BUG - No maps in "Recommended Maps".

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#90]
There are no maps available in "Recommended Maps".
![4](https://cloud.githubusercontent.com/assets/10448932/7855258/547f5b10-0520-11e5-91bb-e164c3e5613c.png)

JLR: "6. List of recommended locations should dynamically generate based on location. Please confirm this list is not hard coded."

What to do with this?

**Comment by w0land** [comment]
This is already implemented and it will be in 1.1.1
