### ISSUE TITLE
BUG - After map is downloaded, user is not able to zoom out the map.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#91]
When new map is downloaded, and user is trying to zoom out, map automatically zooms back.
![5](https://cloud.githubusercontent.com/assets/10448932/7855922/81f01f58-0525-11e5-8c06-9734acf64cb3.png)

**Comment by hubertjadczak** [comment]
When user use Pan functionality to move screen around, and do it before every three seconds pass, there is possibility to zoom the screen out, but it should be done quite fast - Pan should be used every 1-2 seconds.

**Comment by w0land** [comment]
Attach log

**Comment by w0land** [comment]
Clarified with Hubert. Marking as invalid
