### ISSUE TITLE
BUG - Map Orientation functionality is not working.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#92]
Changing Map Orientation is not working:
1:
![6a](https://cloud.githubusercontent.com/assets/10448932/7856219/a6b6b624-0527-11e5-85ec-07f912584d39.png)
2:
![6b](https://cloud.githubusercontent.com/assets/10448932/7856222/ad13e866-0527-11e5-99c9-711b42090a98.png)

**Comment by hubertjadczak** [comment]
After app crash, user was able to set different Map Orientation.

**Comment by w0land** [comment]
Upload log
