### ISSUE TITLE
BUG - Can't add as favourite while in navigation.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#97]
No possibility to add location to favourites during the navigation - tapping on the star icon is not working.
![8](https://cloud.githubusercontent.com/assets/10448932/7856947/2ec8d06a-052d-11e5-8798-a6f510240924.png)

**Comment by w0land** [comment]
Yeah. Which 'location' should be added as favorite? Destination or your current location (current gps position)

**Comment by mmorale1** [comment]
Favoriting always favorite the location in the Location Detail. In the case of Navigation, this would be the destination location. If a new location has been searched or selected on the map while in Navigation, the new location would display in the Location Detail and it would be the location favorited.
