### ISSUE TITLE
BUG - Crash when selecting "Search" in "Search Location menu.

### ISSUE THREAD

**Issue by hubertjadczak** [PDXostc/navit#98]
terminate called after throwing an instance of 'DBus::Error'
  what():  Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Aborted (core dumped)

**Comment by w0land** [comment]
DBus releted problems. Won't fix for now
